services:
  oracle:
    image: gvenzl/oracle-free:full
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_RANDOM_PASSWORD=yes
      - ORACLE_CHARACTERSET=AL32UTF8
      - APP_USER=OAUTH_DEMO_USER
      - APP_USER_PASSWORD=DemoPassword123
    volumes:
      - oracle-data:/opt/oracle/oradata
      - ./scripts/sql/init_scripts:/container-entrypoint-initdb.d
      - ./scripts/sql/startup_scripts:/container-entrypoint-startdb.d
      - ./wallet:/etc/ora_wallet
      - ./certs:/etc/ora_wallet/certs
      - ./scripts/bash:/etc/ora_wallet/scripts
      - ./certs/openiddict-api.crt:/etc/pki/ca-trust/source/anchors/openiddict-api.crt:ro
    command: >
      sh -c "update-ca-trust &&
             /opt/oracle/runOracle.sh"
    networks:
      - app-network

  openiddict-api:
    build:
      context: .
      dockerfile: OpenIddictDemo/Dockerfile
    image: openiddictdemo
    container_name: openiddict-api
    ports:
      - "5112:80"
      - "7104:443"
    environment:
      - USER_SECRETS_ID=open-iddict-demo-027313c3-0f57-44de-bbec-66690428a034
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/openiddict-api.pfx
    volumes:
      - ./certs:/https:ro
      - ~/APPDATA/Roaming/microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    depends_on:
      - mssql
    networks:
      - app-network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  oracle-data:
  sqlserver-data:
